language: node_js
node_js:
  - 9
script:
  - yarn run lint
  - yarn run cover
  - yarn run build
  - yarn run bundlesize
after_success: yarn run coveralls
cache: yarn
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
